
###
get http://localhost:8005/actuator/env

###  Admin login
post http://localhost:8005/oauth/login
Content-Type: application/json

{
  "loginName": "admin0",
  "password": "123456"
}

### User Login
post http://localhost:8005/oauth/login
Content-Type: application/json

{
  "loginName": "tester",
  "password": "123456"
}


### User refresh token
post http://localhost:8005/auth/refresh
Content-Type: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRmZmJmY2I3ZDM4ZjQ2Zjc5NzdiNDU3ODhlMGQ3Njc4In0.eyJqdGkiOiIwREYzcC0wejU3OExaaTZuVzdLVURBIiwiaWF0IjoxNjUyNzA1NjEyLCJleHAiOjE2NTI3MTI4MTIsIm5iZiI6MTY1MjcwNTU1Miwic3ViIjoiYm9va3N0b3JlIiwiYXVkIjoiYXV0aF91c2VyIiwidXNlcklkIjoxLCJ1c2VyVHlwZSI6OTksImxvZ2luTmFtZSI6ImFkbWluMCJ9.k2JrkTAdxYpURjuH8TuJjFXhGz5pMV04OQWWLXlZITSMkVIJRdzKyZPWtUC7q_tbh8nSvm1U8QxZUBICeM3q56rRgEBNE02uzhjOVu8ilt6qzIAjh9E3mQbBrCdRmBwDqqMLhyiA7XuhpEdnw0ttMeaxnDl--fmp5tey4KAmhhfwsKHObmR1_wwJdWdqoK3dpixFtaANHG9xrpyFFOG-OPYosBJHn97gA9vyJhRuwiLmAC2tjoLWzWAtpZc_uX3xxF1daS5Cp11hmnspHXION6ysZUGJZ0YLrqsZ1UiiMGLQjAnO64dE9r9uWM9Yf7o1BED8B0ReZjbgXIyec4uJ3g


### Admin Add BookCategory
post http://localhost:8005/category/addCategory
Content-Type: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRmZmJmY2I3ZDM4ZjQ2Zjc5NzdiNDU3ODhlMGQ3Njc4In0.eyJqdGkiOiI0X05RWDVGZGxxbi1NTWQtb1JFb2pnIiwiaWF0IjoxNjU2MDM2NjUzLCJleHAiOjE2NTYwNDM4NTMsIm5iZiI6MTY1NjAzNjU5Mywic3ViIjoiYm9va3N0b3JlIiwiYXVkIjoiYXV0aF91c2VyIiwidXNlcklkIjoyLCJ1c2VyVHlwZSI6MCwibG9naW5OYW1lIjoidGVzdGVyIn0.LKb06JW3nlac9emYEwiiLOTBK1HxTVnBvdVuXAVc3d2ymXDEICDu5lHSLT5xPxXxXGD5k51g5n2fAIDeAcS1XkpPqKZmt1uGX74DSZRQgnwpPt6lp5tQJhswKNLKUpZOIuhdhMY1BxriL3A82rtbFIsq89r26Z5HTBeSr49anjM5omyvmuIsQwjj4sFd1vnFP4X4iHBuDJTxKnYynDrQZyGwPHSE4U8g2sUW8ZnUkskiXuAMEU4Mtbf5HM2WQED2tZi3CUF50XynQFUIaEuUl_n_v7hNmJXsLCKtaTiVEglIslU_PSKQyKVZolEt_g-lgGlXB2VWMJUatENqw02dgw


{
  "parentId": 0,
  "name": "释经考古",
  "seq": 1,
  "level": 1
}

###
get http://localhost:8005/category/getAll
Content-Type: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRmZmJmY2I3ZDM4ZjQ2Zjc5NzdiNDU3ODhlMGQ3Njc4In0.eyJqdGkiOiI0X05RWDVGZGxxbi1NTWQtb1JFb2pnIiwiaWF0IjoxNjU2MDM2NjUzLCJleHAiOjE2NTYwNDM4NTMsIm5iZiI6MTY1NjAzNjU5Mywic3ViIjoiYm9va3N0b3JlIiwiYXVkIjoiYXV0aF91c2VyIiwidXNlcklkIjoyLCJ1c2VyVHlwZSI6MCwibG9naW5OYW1lIjoidGVzdGVyIn0.LKb06JW3nlac9emYEwiiLOTBK1HxTVnBvdVuXAVc3d2ymXDEICDu5lHSLT5xPxXxXGD5k51g5n2fAIDeAcS1XkpPqKZmt1uGX74DSZRQgnwpPt6lp5tQJhswKNLKUpZOIuhdhMY1BxriL3A82rtbFIsq89r26Z5HTBeSr49anjM5omyvmuIsQwjj4sFd1vnFP4X4iHBuDJTxKnYynDrQZyGwPHSE4U8g2sUW8ZnUkskiXuAMEU4Mtbf5HM2WQED2tZi3CUF50XynQFUIaEuUl_n_v7hNmJXsLCKtaTiVEglIslU_PSKQyKVZolEt_g-lgGlXB2VWMJUatENqw02dgw

### User getById
get http://localhost:8005/book/getById?bookId=1
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRmZmJmY2I3ZDM4ZjQ2Zjc5NzdiNDU3ODhlMGQ3Njc4In0.eyJqdGkiOiIySHFvbDB3ZXR1Uy1qR0ZjT3MtWkxBIiwiaWF0IjoxNjUyMzU3Mzg0LCJleHAiOjE2NTIzNjQ1ODQsIm5iZiI6MTY1MjM1NzMyNCwic3ViIjoiYm9va3N0b3JlIiwiYXVkIjoiYXV0aF91c2VyIiwidXNlcklkIjoxLCJ1c2VyVHlwZSI6OTksImxvZ2luTmFtZSI6ImFkbWluMCJ9.RMdQ__DZGZh0_iAPOnl3aiJgaiKaJOGrtDGBK3gz3h_uPpijs1ZJkQ6WumIyqd3IBlZmdsLAjxU4AeJ5KVp0WRekMurYAuZ9o4MWHsd-gv3S3NHjQFqjLphZqMnBffTd8gWuJ4eDwM7RJeD6ehyUe7YDyOVoosedkVdggZA_xXriIQjW0xOvriSmRU9n5Is-MgWCpVspE6h7m38VlBBsGFN19V34d_uaOJMckHHjExK5iQWKlGzGSZ4hLeQ9ox68H0rBSN9mziKedpc8Olqwf5mvBI0FpzIWH7S7BlGDnad2VH1q8vP6Xr1oLQZN45Npz_932dyZ_LXKxtN0Go9eFQ

### User getByPage
get http://localhost:8005/book/getByPage?pageIndex=1&pageSize=2
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRmZmJmY2I3ZDM4ZjQ2Zjc5NzdiNDU3ODhlMGQ3Njc4In0.eyJqdGkiOiIySHFvbDB3ZXR1Uy1qR0ZjT3MtWkxBIiwiaWF0IjoxNjUyMzU3Mzg0LCJleHAiOjE2NTIzNjQ1ODQsIm5iZiI6MTY1MjM1NzMyNCwic3ViIjoiYm9va3N0b3JlIiwiYXVkIjoiYXV0aF91c2VyIiwidXNlcklkIjoxLCJ1c2VyVHlwZSI6OTksImxvZ2luTmFtZSI6ImFkbWluMCJ9.RMdQ__DZGZh0_iAPOnl3aiJgaiKaJOGrtDGBK3gz3h_uPpijs1ZJkQ6WumIyqd3IBlZmdsLAjxU4AeJ5KVp0WRekMurYAuZ9o4MWHsd-gv3S3NHjQFqjLphZqMnBffTd8gWuJ4eDwM7RJeD6ehyUe7YDyOVoosedkVdggZA_xXriIQjW0xOvriSmRU9n5Is-MgWCpVspE6h7m38VlBBsGFN19V34d_uaOJMckHHjExK5iQWKlGzGSZ4hLeQ9ox68H0rBSN9mziKedpc8Olqwf5mvBI0FpzIWH7S7BlGDnad2VH1q8vP6Xr1oLQZN45Npz_932dyZ_LXKxtN0Go9eFQ


### test GraphQLAPI
post http://localhost:8005/graphql/book
Content-Type: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImRmZmJmY2I3ZDM4ZjQ2Zjc5NzdiNDU3ODhlMGQ3Njc4In0.eyJqdGkiOiIwREYzcC0wejU3OExaaTZuVzdLVURBIiwiaWF0IjoxNjUyNzA1NjEyLCJleHAiOjE2NTI3MTI4MTIsIm5iZiI6MTY1MjcwNTU1Miwic3ViIjoiYm9va3N0b3JlIiwiYXVkIjoiYXV0aF91c2VyIiwidXNlcklkIjoxLCJ1c2VyVHlwZSI6OTksImxvZ2luTmFtZSI6ImFkbWluMCJ9.k2JrkTAdxYpURjuH8TuJjFXhGz5pMV04OQWWLXlZITSMkVIJRdzKyZPWtUC7q_tbh8nSvm1U8QxZUBICeM3q56rRgEBNE02uzhjOVu8ilt6qzIAjh9E3mQbBrCdRmBwDqqMLhyiA7XuhpEdnw0ttMeaxnDl--fmp5tey4KAmhhfwsKHObmR1_wwJdWdqoK3dpixFtaANHG9xrpyFFOG-OPYosBJHn97gA9vyJhRuwiLmAC2tjoLWzWAtpZc_uX3xxF1daS5Cp11hmnspHXION6ysZUGJZ0YLrqsZ1UiiMGLQjAnO64dE9r9uWM9Yf7o1BED8B0ReZjbgXIyec4uJ3g

{
  "query": "query queryBookById($id:Int){queryBookById(id:$id){id,name,author,publishTime,createTime}}",
  "variables": {
    "id": 2 
  }
}